### ISSUE TITLE
Parse Error: The identifier "Godotcord" isn't declared in the current scope

### ISSUE THREAD

**Issue by hugorplobo** [Drachenfrucht1/godotcord#56]
I have this code in my script:

```
func _ready():
	Godotcord.init(CLIENT_ID, Godotcord.CreateFlags_NO_REQUIRE_DISCORD)
	var acv = GodotcordActivity.new()
	acv.state = "just"
	acv.details = "a test"
	acv.large_image = "512"
	acv.large_text = "Left Out"
	GodotcordActivityManager.set_activity(acv)

func _process(delta):
	Godotcord.run_callbacks()
```

When I run the game inside the editor, it works fine, but when I export it, I get this:

![Error :(](https://i.ibb.co/1MHMxJP/eror.jpg)

All the dlls are in the same game's directory.

**Comment by summertimejordi** [comment]
You need to compile Godot's export templates with the Godotcord module. Learn more here:
[Windows](https://docs.godotengine.org/en/stable/development/compiling/compiling_for_windows.html?#creating-windows-export-templates)
[Linux](https://docs.godotengine.org/en/stable/development/compiling/compiling_for_x11.html?#building-export-templates)
[More info](https://docs.godotengine.org/en/stable/development/compiling/introduction_to_the_buildsystem.html)

Godot can't find Godotcord in the export because it packages a copy of Godot without the editor with your game. If you don't build a copy of Godot with Godot to be used in the export, it won't include Godotcord

Hope this helps.

**Comment by hugorplobo** [comment]
I downloaded the compiled version from github because I was having some issues with compilation. So, I need to compile the godot anyaway? I read in the link you send that there is how to configure binaries as custom exports in case of custom modules, but I didn't understand how to do it. Sorry for the questions, but I don't have experience with "compiled things".

**Comment by summertimejordi** [comment]
> ...I read in the link you send that there is how to configure binaries as custom exports in case of custom modules, but I didn't understand how to do it...

Yeah so first you have to get the source code for Godot. Open a terminal and run `git clone -b 3.2 https://github.com/godotengine/godot`. Then, run `cd godot/modules && git clone https://github.com/drachenfrucht1/godotcord`. If you're on Linux/Mac, run `./setup.sh` in the terminal.
If you're on Windows: run `./setup.bat`.
From there, cd back to the root directory of godot: `cd ../` and follow [this](https://docs.godotengine.org/en/stable/development/compiling/index.html) to compile for your platform. Keep in mind that if you're only looking to compile export templates, you have to use `tools=no` in your SCons command.

**Comment by Drachenfrucht1** [comment]
You can set the downloaded version as export templates. This works, but I do not recommend it for shipping. It should be fine for testing.
The specially compiled export templates don't include the engine frontend (and no debug symbols when using the release version). This greatly reduces the size.

**Comment by hugorplobo** [comment]
Thanks for the help guys, the export is working after the compiling.
